# Generated by Django 5.1.2 on 2025-06-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0006_leavetype_is_mandatory_leave_alter_leavetype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='mandatory_annual_quota',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='mandatory_remaining',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavemanagement',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
