# Generated by Django 5.1.2 on 2025-06-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0009_alter_leavebalance_mandatory_annual_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='mandatory_remaining',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
