# Generated by Django 5.1.2 on 2025-06-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0010_alter_leavebalance_mandatory_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='mandatory_annual_quota',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='mandatory_remaining',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
