# Generated by Django 5.1.2 on 2025-06-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0012_alter_leavebalance_mandatory_annual_quota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='mandatory_annual_quota',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='mandatory_remaining',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
