# Generated by Django 5.1.2 on 2025-01-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance', '0003_leavetype_alter_leaverequest_employee_leavesummary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leaverecord',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leaverecord',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='leavesummary',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
        migrations.DeleteModel(
            name='LeaveRecord',
        ),
        migrations.DeleteModel(
            name='LeaveType',
        ),
        migrations.DeleteModel(
            name='leavesummary',
        ),
    ]
