# Generated by Django 5.1.2 on 2025-01-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance', '0010_noninvolvementcertificate_delete_nicrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noninvolvementcertificate',
            name='employee_name',
        ),
    ]
