# Generated by Django 5.1.2 on 2025-01-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance', '0012_rename_renewal_date_contractrenewal_contract_expiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractrenewal',
            old_name='Contract_expiry_date',
            new_name='contract_expiry',
        ),
    ]
