# Generated by Django 5.1.2 on 2025-01-07 15:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance', '0014_rename_contractrenewal_contractrenewall'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractRenewall',
            new_name='ContractRenewal',
        ),
        migrations.RenameField(
            model_name='contractrenewal',
            old_name='contract_expiry',
            new_name='contract_expiry_date',
        ),
    ]
