# Generated by Django 5.1.2 on 2025-01-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance', '0019_contractualleaverecord_application_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='availed_leaves',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
