# Generated by Django 5.1.2 on 2025-01-28 14:32

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance', '0021_leaveapplication_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='educationaldocument',
            name='document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
