# Generated by Django 5.1.2 on 2025-05-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance', '0024_remove_leaveapplication_backup_employee1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='application_type',
            field=models.CharField(choices=[('Casual', 'Casual Leave'), ('Privilege', 'Privilege Leave'), ('Sick', 'Sick Leave'), ('Mandatory ', 'Mandatory Leave'), ('Ex-Pakistan', 'Ex-Pakistan Leave')], max_length=100),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='supervisor_signature',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
