# Generated by Django 5.1.2 on 2025-01-06 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance', '0007_leaveapplication_delete_casualleaveapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('renewal_date', models.DateField()),
                ('reason', models.TextField()),
                ('renewal_document', models.FileField(upload_to='renewal_documents/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_renewals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
