# Generated by Django 5.1.2 on 2025-01-07 15:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance', '0013_rename_contract_expiry_date_contractrenewal_contract_expiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractRenewal',
            new_name='ContractRenewall',
        ),
    ]
