# Generated by Django 5.1.2 on 2025-01-08 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance', '0015_rename_contractrenewall_contractrenewal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermanentLeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('total_leaves', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='application_type',
            field=models.CharField(choices=[('Casual', 'Casual Leave'), ('Privilege', 'Privilege Leave'), ('Sick', 'Sick Leave')], max_length=100),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ContractualLeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.TextField()),
                ('application_type', models.CharField(choices=[('Casual', 'Casual Leave'), ('Sick', 'Sick Leave')], max_length=100)),
                ('supervisor_signature', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractual_leave_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='LeaveType',
            new_name='ContractualLeaveType',
        ),
        migrations.CreateModel(
            name='ContractualLeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availed_leaves', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractual_leave_records', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_attendance.contractualleavetype')),
            ],
        ),
        migrations.AlterField(
            model_name='leaverecord',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_attendance.permanentleavetype'),
        ),
    ]
