# Generated by Django 5.1.2 on 2025-01-09 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance', '0017_alter_contractualleaverecord_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractualleaverecord',
            name='leave_type',
        ),
    ]
