# Generated by Django 5.1.2 on 2025-01-10 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance', '0018_remove_contractualleaverecord_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractualleaverecord',
            name='application_type',
            field=models.ForeignKey(choices=[('Casual', 'Casual Leave'), ('Sick', 'Sick Leave')], default=None, on_delete=django.db.models.deletion.CASCADE, to='employee_attendance.contractualleaveapplication'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='from_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='to_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
