# Generated by Django 5.1.2 on 2025-01-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance', '0020_leaveapplication_availed_leaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
