# Generated by Django 5.1.2 on 2025-01-13 17:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance', '0020_leaveapplication_availed_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationaldocument',
            name='document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
