# Generated by Django 5.1.2 on 2025-01-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance', '0021_alter_educationaldocument_document'),
        ('employee_attendance', '0022_leaveapplication_status'),
    ]

    operations = [
    ]
