# Generated by Django 5.1.2 on 2025-04-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance', '0023_leaveapplication_backup_employee1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='backup_employee1',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='backup_employee2',
        ),
    ]
