# Generated by Django 5.1.2 on 2025-05-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance', '0025_alter_leaveapplication_application_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractualleaveapplication',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='contractualleaverecord',
            name='application_type',
        ),
        migrations.RemoveField(
            model_name='contractualleaverecord',
            name='employee',
        ),
        migrations.DeleteModel(
            name='ContractualLeaveType',
        ),
        migrations.RemoveField(
            model_name='leaverecordcontractual',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leaverecordpremanent',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leaverecordpremanent',
            name='leave_type',
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='application_type',
            field=models.CharField(choices=[('Casual', 'Casual Leave'), ('Privilege', 'Privilege Leave'), ('Sick', 'Sick Leave'), ('Mandatory', 'Mandatory Leave'), ('Ex-Pakistan', 'Ex-Pakistan Leave')], max_length=100),
        ),
        migrations.DeleteModel(
            name='ContractualLeaveApplication',
        ),
        migrations.DeleteModel(
            name='ContractualLeaveRecord',
        ),
        migrations.DeleteModel(
            name='LeaveRecordContractual',
        ),
        migrations.DeleteModel(
            name='LeaveRecordPremanent',
        ),
        migrations.DeleteModel(
            name='PermanentLeaveType',
        ),
    ]
