# Generated by Django 5.1.2 on 2025-06-18 15:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0052_apa_grading'),
        ('employee_attendance', '0026_remove_contractualleaveapplication_employee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Privileged', 'Privileged Leave'), ('Casual', 'Casual Leave'), ('Sick', 'Sick Leave'), ('Ex-Pakistan', 'Ex-Pakistan Leave'), ('Mandatory', 'Mandatory Leave')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField(default=datetime.date.today)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('availed_leaves', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField()),
                ('supervisor_signature', models.CharField(blank=True, max_length=100, null=True)),
                ('leave_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('with_station_permission', models.BooleanField(default=False, help_text='Permission to leave station')),
                ('extension_allowed', models.BooleanField(default=False, help_text='Whether leave extension is allowed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_leave_applications', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_attendance.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('grant', 'Annual Grant'), ('usage', 'Leave Usage'), ('carry_forward', 'Carry Forward'), ('freeze', 'Freeze Leaves'), ('expire', 'Leave Expiry'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('transaction_date', models.DateField(default=datetime.date.today)),
                ('days', models.IntegerField(help_text='Positive for additions, negative for deductions')),
                ('year', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_transactions', to=settings.AUTH_USER_MODEL)),
                ('leave_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_attendance.employeeleaveapplication')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_attendance.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='LeavePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_month', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('start_day', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)])),
                ('end_month', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('end_day', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)])),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRIS_App.employeetype')),
            ],
            options={
                'unique_together': {('employee_type', 'start_month', 'start_day')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_entitlement', models.PositiveIntegerField(help_text='Annual leave entitlement in days')),
                ('can_freeze', models.BooleanField(default=False, help_text='Whether unused leaves can be frozen for future use')),
                ('min_consumption_required', models.PositiveIntegerField(default=0, help_text='Minimum number of days that must be consumed annually')),
                ('carry_forward_limit', models.PositiveIntegerField(default=0, help_text='Maximum days that can be carried forward')),
                ('carry_forward_expiry_months', models.PositiveIntegerField(default=3, help_text='Number of months after which carried forward leaves expire')),
                ('is_active', models.BooleanField(default=True)),
                ('employee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRIS_App.employeetype')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_attendance.leavetype')),
            ],
            options={
                'verbose_name': 'Employee Leave Policy',
                'verbose_name_plural': 'Employee Leave Policies',
                'unique_together': {('employee_type', 'leave_type')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('entitled_leaves', models.PositiveIntegerField(default=0)),
                ('carried_forward_leaves', models.PositiveIntegerField(default=0)),
                ('carried_forward_expiry_date', models.DateField(blank=True, null=True)),
                ('used_leaves', models.PositiveIntegerField(default=0)),
                ('frozen_leaves', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_attendance.leavetype')),
            ],
            options={
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
