# Generated by Django 5.1.2 on 2025-06-19 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance', '0027_leavetype_employeeleaveapplication_leavetransaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetransaction',
            name='leave_application',
        ),
        migrations.AlterUniqueTogether(
            name='employeeleavebalance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='employeeleavebalance',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeleavebalance',
            name='leave_type',
        ),
        migrations.AlterUniqueTogether(
            name='employeeleavepolicy',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='employeeleavepolicy',
            name='employee_type',
        ),
        migrations.RemoveField(
            model_name='employeeleavepolicy',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='employee',
        ),
        migrations.AlterUniqueTogether(
            name='leaveperiod',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='leaveperiod',
            name='employee_type',
        ),
        migrations.RemoveField(
            model_name='leavetransaction',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leavetransaction',
            name='leave_type',
        ),
        migrations.DeleteModel(
            name='EmployeeLeaveApplication',
        ),
        migrations.DeleteModel(
            name='EmployeeLeaveBalance',
        ),
        migrations.DeleteModel(
            name='EmployeeLeavePolicy',
        ),
        migrations.DeleteModel(
            name='LeaveApplication',
        ),
        migrations.DeleteModel(
            name='LeavePeriod',
        ),
        migrations.DeleteModel(
            name='LeaveTransaction',
        ),
        migrations.DeleteModel(
            name='LeaveType',
        ),
    ]
