# Generated by Django 5.1.2 on 2024-11-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_employees', '0002_rename_employee_inquiry_admin_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='transferred_employee',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
