# Generated by Django 5.1.2 on 2024-11-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_employees', '0003_inquiry_transferred_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name': 'Transfer Inquiry', 'verbose_name_plural': 'Transfer Inquiries'},
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='remarks',
            new_name='transfer_remarks',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='pending_inquiry',
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='admin_action',
            field=models.CharField(choices=[('close', 'close'), ('approved', 'Approved'), ('rejected', 'Rejected')], default=' ', max_length=100),
        ),
    ]
