# Generated by Django 5.1.2 on 2025-06-13 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_rename_templattemplate_saved_url_permenantlettertemplates_template_saved_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('Father of', 'Father of'), ('Mother of', 'Mother of'), ('Son of', 'Son of'), ('Daughter of', 'Daughter of'), ('Wife of', 'Wife of'), ('Husband of', 'Husband of')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalizationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('Self', 'Self'), ('Family/Dependents', 'Family/Dependents')], max_length=20)),
                ('purpose', models.TextField()),
                ('hospital_name', models.CharField(max_length=100)),
                ('pdf_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalization_forms', to=settings.AUTH_USER_MODEL)),
                ('family_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.familymember')),
            ],
        ),
    ]
