# Generated by Django 5.1.2 on 2025-06-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0010_purpose_alter_hospitalizationform_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='marital_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
