# Generated by Django 5.1.2 on 2025-06-16 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0013_pulicholidays_date_alter_pulicholidays_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pulicholidays',
            options={'ordering': ['date'], 'verbose_name': 'Public Holiday', 'verbose_name_plural': 'Public Holidays'},
        ),
    ]
