# Generated by Django 5.1.2 on 2025-07-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0015_alter_familymember_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenditureHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expenditure Head',
                'verbose_name_plural': 'Expenditure Heads',
            },
        ),
    ]
