# Generated by Django 5.1.2 on 2025-07-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0016_expenditurehead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pulicholidays",
            name="day",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
