# Generated by Django 5.1.2 on 2024-11-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0007_remove_employee_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_group',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
