# Generated by Django 5.1.2 on 2024-11-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0011_remove_employee_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pending_inquiry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
