# Generated by Django 5.1.2 on 2024-11-20 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0012_employee_pending_inquiry_employee_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRIS_App.region', to_field='name'),
        ),
    ]
