# Generated by Django 5.1.2 on 2024-11-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0014_employee_region_alter_branch_branch_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='head_office',
            field=models.BooleanField(default=False),
        ),
    ]
