# Generated by Django 5.1.2 on 2024-11-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0017_remove_employee_phone_no_official_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='transferred_status',
            field=models.CharField(blank=True, choices=[('within_group', 'Transferred within Group'), ('outside_group', 'Transferred outside Group')], max_length=20, null=True),
        ),
    ]
