# Generated by Django 5.1.2 on 2024-11-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0019_alter_branch_options_alter_division_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_email',
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email'),
        ),
    ]
