# Generated by Django 5.1.2 on 2024-11-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0020_remove_employee_employee_email_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='grade_assignment',
            field=models.CharField(blank=True, choices=[('A', 'A - 20%'), ('B', 'B - 25%'), ('C', 'C - 40%'), ('D', 'D - 10%'), ('E', 'E - 5%')], max_length=1, null=True),
        ),
    ]
