# Generated by Django 5.1.2 on 2024-11-25 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0022_region_region_id_alter_employee_grade_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='branch_region',
        ),
        migrations.AddField(
            model_name='branch',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRIS_App.region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_id',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
