# Generated by Django 5.1.2 on 2024-11-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0025_alter_branch_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(max_length=500),
        ),
    ]
