# Generated by Django 5.1.2 on 2024-11-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0027_alter_employee_date_current_assignment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '  Group'},
        ),
    ]
