# Generated by Django 5.1.2 on 2024-12-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0029_alter_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='A_Grade_seats',
            field=models.FloatField(default=15.0),
        ),
        migrations.AddField(
            model_name='region',
            name='B_Grade_seats',
            field=models.FloatField(default=20.0),
        ),
        migrations.AddField(
            model_name='region',
            name='C_Grade_seats',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='region',
            name='D_Grade_seats',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='region',
            name='E_Grade_seats',
            field=models.FloatField(default=5.0),
        ),
    ]
