# Generated by Django 5.1.2 on 2024-12-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0034_alter_region_csv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_user',
            field=models.BooleanField(default=True),
        ),
    ]
