# Generated by Django 5.1.2 on 2024-12-24 17:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0035_employee_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='csv_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
