# Generated by Django 5.1.2 on 2025-01-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0038_employee_first_appraiser_employee_review_period_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='date_of_last_promotion',
            new_name='date_of_retirement',
        ),
    ]
