# Generated by Django 5.1.2 on 2025-04-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0041_alter_employee_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='phone_no_emergency_contact',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_salutation',
            field=models.CharField(blank=True, default='MR.', max_length=15, null=True),
        ),
    ]
