# Generated by Django 5.1.2 on 2025-04-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0042_remove_employee_phone_no_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_letter_templte_admin',
            field=models.BooleanField(default=False),
        ),
    ]
