# Generated by Django 5.1.2 on 2025-05-05 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0046_remove_division_functional_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wing',
            old_name='division',
            new_name='division_name',
        ),
        migrations.RemoveField(
            model_name='region',
            name='functional_group',
        ),
    ]
