# Generated by Django 5.1.2 on 2025-05-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0047_rename_division_wing_division_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='in_active_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
