# Generated by Django 5.1.2 on 2025-06-17 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0051_alter_employee_cnic_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='APA_Grading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('Outstanding', 'O'), ('Very Good', 'VG'), ('Good', 'G'), ('Needs Improvement', 'NI'), ('Unsatisfactory', 'US')], default='Not Assigned', max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apa_grading', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'APA Grading',
                'verbose_name_plural': ' APA Gradings',
            },
        ),
    ]
