# Generated by Django 5.1.2 on 2025-07-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0054_employee_division_employee_wing'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='iban',
            field=models.CharField(blank=True, help_text='International Bank Account Number', max_length=50, null=True),
        ),
    ]
