# Generated by Django 5.1.2 on 2025-07-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HRIS_App", "0055_employee_iban"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="job_description",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="successor",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
