# Generated by Django 5.1.2 on 2025-07-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HRIS_App", "0056_employee_job_description_employee_successor"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="date_of_last_promotion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
