# Generated by Django 5.1.2 on 2025-06-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Privileged', 'Privileged Leave'), ('Casual', 'Casual Leave'), ('Sick', 'Sick Leave'), ('Ex-Pakistan', 'Ex-Pakistan Leave'), ('Mandatory', 'Mandatory Leave')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
