# Generated by Django 5.1.2 on 2025-06-19 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_leavebalance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveCycle',
        ),
    ]
