# Generated by Django 5.1.2 on 2025-06-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0004_delete_leavecycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemanagement',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
