# Generated by Django 5.1.2 on 2025-06-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0005_alter_leavemanagement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_mandatory_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(choices=[('Privileged', 'Privileged Leave'), ('Casual', 'Casual Leave'), ('Sick', 'Sick Leave'), ('Ex-Pakistan', 'Ex-Pakistan Leave')], max_length=50),
        ),
    ]
