# Generated by Django 5.1.2 on 2025-06-30 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0007_leavebalance_is_mandatory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='frozenleavebalance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frozen_leave_balances', to=settings.AUTH_USER_MODEL, to_field='SAP_ID'),
        ),
    ]
