# Generated by Django 5.1.2 on 2025-06-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0008_alter_frozenleavebalance_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='mandatory_annual_quota',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
