# Generated by Django 5.1.2 on 2024-12-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ricpdata',
            options={'verbose_name': 'Risk, Internal Controls & Processes'},
        ),
        migrations.AlterModelOptions(
            name='ricpkpi',
            options={'verbose_name': 'RICP KPI'},
        ),
        migrations.AlterField(
            model_name='ricpkpi',
            name='weightage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
