# Generated by Django 5.1.2 on 2024-12-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_user', '0002_alter_ricpdata_options_alter_ricpkpi_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ricpdata',
            name='full_year_review',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ricpdata',
            name='half_year_review',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
