# Generated by Django 5.1.2 on 2024-12-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_user', '0003_alter_ricpdata_full_year_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ricpdata',
            name='balance_score_card_form_type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
