# Generated by Django 5.1.2 on 2024-12-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_user', '0004_ricpdata_balance_score_card_form_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ricpdata',
            name='balance_score_card_form_type',
        ),
        migrations.AddField(
            model_name='ricpkpi',
            name='bsc_form_type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
