# Generated by Django 5.1.2 on 2024-12-23 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RicpData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('half_year_review', models.CharField(blank=True, choices=[('outstanding', 'Outstanding'), ('very_good', 'Very Good'), ('good', 'Good'), ('needs_improvement', 'Needs Improvement'), ('unsatisfactory', 'Unsatisfactory')], max_length=20, null=True)),
                ('full_year_review', models.CharField(blank=True, choices=[('outstanding', 'Outstanding'), ('very_good', 'Very Good'), ('good', 'Good'), ('needs_improvement', 'Needs Improvement'), ('unsatisfactory', 'Unsatisfactory')], max_length=20, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ricp_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RicpKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi', models.TextField()),
                ('achievement', models.TextField()),
                ('weightage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('ricp_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='employee_user.ricpdata')),
            ],
        ),
    ]
