# Generated by Django 5.1.2 on 2024-12-30 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_user', '0005_remove_ricpdata_balance_score_card_form_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ricpdata',
            options={'verbose_name': 'Balance ScoreCard Employee'},
        ),
        migrations.AlterModelOptions(
            name='ricpkpi',
            options={'verbose_name': 'Balance ScoreCard Form'},
        ),
    ]
