# Generated by Django 5.1.2 on 2025-01-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_user', '0006_alter_ricpdata_options_alter_ricpkpi_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ricpdata',
            name='final_score',
        ),
        migrations.AddField(
            model_name='ricpkpi',
            name='form_final_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
