# Generated by Django 5.1.2 on 2025-07-04 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_user", "0007_remove_ricpdata_final_score_ricpkpi_form_final_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedEmployees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sap_id", models.IntegerField(unique=True, verbose_name="SAP ID")),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("branch", models.CharField(blank=True, max_length=500, null=True)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "employee_grade",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "employee_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "date_of_joining",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("deletion_reason", models.TextField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_employees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Deleted Employee",
                "verbose_name_plural": "Deleted Employees",
                "ordering": ["-deleted_at"],
            },
        ),
    ]
