# Generated by Django 5.1.2 on 2025-07-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_user", "0008_deletedemployees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deletedemployees",
            name="region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Resigned", "Resigned"),
                    ("Transfered out of Group", "Transfered out of Group"),
                    ("Deceased", "Deceased"),
                    ("Retired", "Retired"),
                    ("Terminated", "Terminated"),
                    ("Suspended", "Suspended"),
                    ("Contract Expired", "Contract Expired"),
                    ("Other", "Other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
