# Generated by Django 5.1.2 on 2025-03-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signature',
            old_name='employee',
            new_name='employee_name',
        ),
    ]
