# Generated by Django 5.1.2 on 2025-03-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_rename_employee_signature_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='SAP_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
