# Generated by Django 5.1.2 on 2025-04-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_hospitalname'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettertemplates',
            name='template_saved_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
