# Generated by Django 5.1.2 on 2025-05-01 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_remove_lettertemplates_template_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permenantlettertemplates',
            old_name='templattemplate_saved_url',
            new_name='template_saved_url',
        ),
    ]
