# Generated by Django 5.1.2 on 2025-06-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0012_pulicholidays'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulicholidays',
            name='date',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pulicholidays',
            name='day',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
