# Generated by Django 5.1.2 on 2025-06-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0014_alter_pulicholidays_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
