# Generated by Django 5.1.2 on 2024-11-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0001_initial'),
    ]

    operations = [
    ]
