# Generated by Django 5.1.2 on 2024-11-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0002_auto_20241115_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AddField(
            model_name='employee',
            name='admin_signuture',
            field=models.BooleanField(default=False),
        ),
    ]
