# Generated by Django 5.1.2 on 2024-11-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0005_rename_date_of_retirement_employee_date_of_joining'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_group',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
