# Generated by Django 5.1.2 on 2024-11-19 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0006_employee_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user_group',
        ),
    ]
