# Generated by Django 5.1.2 on 2024-11-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0009_remove_employee_admin_signuture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='is_approved',
            new_name='is_admin_employee',
        ),
    ]
