# Generated by Django 5.1.2 on 2024-11-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0010_rename_is_approved_employee_is_admin_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='full_name',
        ),
    ]
