# Generated by Django 5.1.2 on 2024-11-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0015_branch_head_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='head_office',
        ),
        migrations.AddField(
            model_name='region',
            name='head_office',
            field=models.BooleanField(default=False),
        ),
    ]
