# Generated by Django 5.1.2 on 2024-11-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0016_remove_branch_head_office_region_head_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='phone_no_official',
        ),
        migrations.AddField(
            model_name='employee',
            name='transferred_status',
            field=models.CharField(blank=True, choices=[('within_group', 'Transferred within Group'), ('outside_group', 'Transferred outside Group')], default='within_group', max_length=20, null=True),
        ),
    ]
