# Generated by Django 5.1.2 on 2024-11-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0024_alter_branch_region_alter_employee_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
