# Generated by Django 5.1.2 on 2024-11-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0026_alter_branch_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_current_assignment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_current_posting',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_last_promotion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
