# Generated by Django 5.1.2 on 2024-12-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0030_region_a_grade_seats_region_b_grade_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='grade_assignment',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Needs Improvement', 'Needs Improvement'), ('Unsatisfactory', 'Unsatisfactory'), ('Not Assigned', 'Not Assigned')], default='Not Assigned', max_length=100, null=True),
        ),
    ]
