# Generated by Django 5.1.2 on 2024-12-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0031_alter_employee_grade_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='csv_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='CSV_Files'),
        ),
    ]
