# Generated by Django 5.1.2 on 2024-12-24 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0036_employee_csv_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='csv_file',
            new_name='pdf_file',
        ),
    ]
