# Generated by Django 5.1.2 on 2025-01-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0039_rename_date_of_last_promotion_employee_date_of_retirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_contract_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='place_of_posting',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
