# Generated by Django 5.1.2 on 2025-04-08 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0043_employee_is_letter_templte_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='is_letter_templte_admin',
            new_name='is_letter_template_admin',
        ),
    ]
