# Generated by Django 5.1.2 on 2025-05-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0044_rename_is_letter_templte_admin_employee_is_letter_template_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region_id',
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
