# Generated by Django 5.1.2 on 2025-05-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0045_alter_region_region_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='functional_group',
        ),
        migrations.AlterField(
            model_name='division',
            name='division_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wing',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
