# Generated by Django 5.1.2 on 2025-06-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0050_employee_groups_employee_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cnic_no',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
