# Generated by Django 5.1.2 on 2025-06-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0052_apa_grading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apa_grading',
            name='grade',
            field=models.CharField(choices=[('O', 'Outstanding'), ('VG', 'Very Good'), ('G', 'Good'), ('NI', 'Needs Improvement'), ('US', 'Unsatisfactory')], default='Not Assigned', max_length=100),
        ),
    ]
