# Generated by Django 5.1.2 on 2025-07-01 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRIS_App', '0053_alter_apa_grading_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='HRIS_App.division', to_field='division_name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='wing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='HRIS_App.wing', to_field='name'),
        ),
    ]
