# Generated by Django 5.1.2 on 2024-11-21 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='employee',
            new_name='admin_employee',
        ),
    ]
